name: Somanda
favicon: null
layout_spectrum: 0.690533958375454
typography_spectrum: 0.11843722802586854
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ADD7F6'
    - '#87BFFF'
    - '#3F8EFC'
    - '#2667FF'
    - '#3B28CC'
  brandStrength: 0.36499040434136987
  lightness: 0.8065079271327704
  saturation: 0.35483646555803716
  rhythmicContrast: 0.7685727297794074
purpose: []
